# Unlikely to need customization
tmp_video_download_path: "/google-api-automation/video_transit_dir/"
global_privacy: "public" # public/private
youtube_base_url: "https://youtu.be/"

# Likely to need customization
khan_youtube_id: "UCHNKwF_1cac1ebnOtrdXwVw"
gdoc_sheet_url: "https://docs.google.com/spreadsheets/d/1WE3ba2vsrJLaVs_0ih6GEUz6hozTyEvKr1VJs023KsY/edit#gid=0"
title_col: "D"
description_col: "E"
course_description_col: "F"
markers_col: "G"
eng_video_id: "C"
ka_youtube_url_col: "H"
sheet_name: "Sheet1"

# Sheet dimensions
range_starting_col: "A"
first_row: 2
range_ending_col: "H"
last_row: 4
